### ISSUE TITLE
Accessibility: TODO

### ISSUE THREAD

**Issue by brumik** [brumik/react-wooden-tree#20]
ToDo list till completion of accessibility:
* [ ] Find a way to completely disable accessibility for the sake of performance. 
* [ ] Convert from demo to the main component: do not forget update packages.json as well.
* [ ] Test writing!
* [ ] Documentation update.
* [ ] NPM new release
